import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './header/header.component';
import { SidebarComponent } from './sidebar/sidebar.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet,HeaderComponent,SidebarComponent,CommonModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit{
  title = 'smart-pal';

  initialData = [
    {
      id: '1',
      equipmentCode: '101.1',
      equipmentName: 'Equipment-1',
      parentEquipment: 'Equipment-1 parent',
      model: '950',
      marker: 'INDIA',
      equipmentType: 'boston',
      drawingNo: 'boston',
      vesselClass: 'boston',
      vesselName: 'vessel-1-eqp',
      department: 'mariapps',
      type: 'boston',
      safetyLevel: 'boston',
      maker: '',
      mariAppsRef: '',
      builder: 'boston',
      partNumber: 'boston',
      inheritRHrsFrom: '',
      RHrsSeparately: '',
      mountAllowed: '',
      circulating: '',
      legacyCode: '',
      active: false,
      lastModifiedUser: '',
      lastModifiedDate: '',
      preferredVendor: '',
      installationDate: '3/10/2000', 
      equipmentDimension: '',
      equipmentMaterial: '',
      maerskArtCode: '',
      circulatingEquipment: 'boston',
      remarks: '',
      applicableVessel: '',
      builderLicense: 'boston',
    },
    {
      id: '2',
      equipmentCode: '101.2',
      equipmentName: 'Equipment-2',
      parentEquipment: 'Equipment-2 parent',
      model: '950',
      marker: 'INDIA',
      equipmentType: 'chicago',
      drawingNo: 'chicago',
      vesselClass: 'chicago',
      vesselName: 'vessel-2-eqp',
      department: 'mariapps',
      type: 'chicago',
      safetyLevel: 'chicago',
      maker: '',
      mariAppsRef: '',
      builder: 'chicago',
      partNumber: 'chicago',
      inheritRHrsFrom: '',
      RHrsSeparately: '',
      mountAllowed: '',
      circulating: '',
      legacyCode: '',
      active: false,
      lastModifiedUser: '',
      lastModifiedDate: '',
      preferredVendor: '',
      installationDate: '3/10/2000', 
      equipmentDimension: '',
      equipmentMaterial: '',
      maerskArtCode: '',
      circulatingEquipment: 'chicago',
      remarks: '',
      applicableVessel: '',
      builderLicense: 'boston',
    },
    {
      id: '3',
      equipmentCode: '101.3',
      equipmentName: 'Equipment-3',
      parentEquipment: 'Equipment-3 parent',
      model: '950',
      marker: 'INDIA',
      equipmentType: 'boston',
      drawingNo: 'boston',
      vesselClass: 'boston',
      vesselName: 'vessel-3-eqp',
      department: 'mariapps',
      type: 'boston',
      safetyLevel: 'boston',
      maker: '',
      mariAppsRef: '',
      builder: 'boston',
      partNumber: 'boston',
      inheritRHrsFrom: '',
      RHrsSeparately: '',
      mountAllowed: '',
      circulating: '',
      legacyCode: '',
      active: true,
      lastModifiedUser: '',
      lastModifiedDate: '',
      preferredVendor: '',
      installationDate: '3/10/2000', 
      equipmentDimension: '',
      equipmentMaterial: '',
      maerskArtCode: '',
      circulatingEquipment: 'boston',
      remarks: '',
      applicableVessel: '',
      builderLicense: 'boston',
    },
    {
      id: '4',
      equipmentCode: '201.1',
      equipmentName: 'Equipment-2-1',
      parentEquipment: 'Equipment-2-1 parent',
      model: '950',
      marker: 'INDIA',
      equipmentType: 'boston',
      drawingNo: 'boston',
      vesselClass: 'boston',
      vesselName: 'vessel-2-1-eqp',
      department: 'mariapps',
      type: 'boston',
      safetyLevel: 'boston',
      maker: '',
      mariAppsRef: '',
      builder: 'boston',
      partNumber: 'boston',
      inheritRHrsFrom: '',
      RHrsSeparately: '',
      mountAllowed: '',
      circulating: '',
      legacyCode: '',
      active: true,
      lastModifiedUser: '',
      lastModifiedDate: '',
      preferredVendor: '',
      installationDate: '3/10/2000', 
      equipmentDimension: '',
      equipmentMaterial: '',
      maerskArtCode: '',
      circulatingEquipment: 'boston',
      remarks: '',
      applicableVessel: '',
      builderLicense: 'boston',
    },
    {
      id: '5',
      equipmentCode: '201.2',
      equipmentName: 'Equipment-2',
      parentEquipment: 'Equipment-2 parent',
      model: '950',
      marker: 'INDIA',
      equipmentType: 'boston',
      drawingNo: 'boston',
      vesselClass: 'boston',
      vesselName: 'vessel-2.3-eqp',
      department: 'mariapps',
      type: 'boston',
      safetyLevel: 'boston',
      maker: '',
      mariAppsRef: '',
      builder: 'boston',
      partNumber: 'boston',
      inheritRHrsFrom: '',
      RHrsSeparately: '',
      mountAllowed: '',
      circulating: '',
      legacyCode: '',
      active: false,
      lastModifiedUser: '',
      lastModifiedDate: '',
      preferredVendor: '',
      installationDate: '3/10/2000', 
      equipmentDimension: '',
      equipmentMaterial: '',
      maerskArtCode: '',
      circulatingEquipment: 'boston',
      remarks: '',
      applicableVessel: '',
      builderLicense: 'boston',
    },
    {
      id: '6',
      equipmentCode: '201.3',
      equipmentName: 'Equipment-2-3',
      parentEquipment: 'Equipment-2-3 parent',
      model: '950',
      marker: 'INDIA',
      equipmentType: 'boston',
      drawingNo: 'boston',
      vesselClass: 'boston',
      vesselName: 'vessel-2-3-eqp',
      department: 'mariapps',
      type: 'boston',
      safetyLevel: 'boston',
      maker: '',
      mariAppsRef: '',
      builder: 'boston',
      partNumber: 'boston',
      inheritRHrsFrom: '',
      RHrsSeparately: '',
      mountAllowed: '',
      circulating: '',
      legacyCode: '',
      active: false,
      lastModifiedUser: '',
      lastModifiedDate: '',
      preferredVendor: '',
      installationDate: '3/10/2000', 
      equipmentDimension: '',
      equipmentMaterial: '',
      maerskArtCode: '',
      circulatingEquipment: 'boston',
      remarks: '',
      applicableVessel: '',
      builderLicense: 'boston',
    },
  ];

  data = [
    {
      id: '1',
      equipmentCode: '101.1',
      equipmentName: 'Equipment-1',
      parentEquipment: 'Equipment-1 parent',
      equipment: '02',
      jobplan: '03',
      mappedVessel: '02',
      spareParts: '05',
      serviceLetter: '00',
      userManual: '00'
    },
    {
      id: '2',
      equipmentCode: '102.2',
      equipmentName: 'Equipment-2',
      parentEquipment: 'Equipment-2 parent',
      equipment: '12',
      jobplan: '23',
      mappedVessel: '08',
      spareParts: '02',
      serviceLetter: '00',
      userManual: '00'
    },
    {
      id: '3',
      equipmentCode: '101.3',
      equipmentName: 'Equipment-3',
      parentEquipment: 'Equipment-3 parent',
      equipment: '04',
      jobplan: '33',
      mappedVessel: '05',
      spareParts: '03',
      serviceLetter: '00',
      userManual: '00'
    },
    {
      id: '4',
      equipmentCode: '101.4',
      equipmentName: 'Equipment-4',
      parentEquipment: 'Equipment-4 parent',
      equipment: '04',
      jobplan: '14',
      mappedVessel: '05',
      spareParts: '03',
      serviceLetter: '00',
      userManual: '00'
    },
  ]

  ngOnInit(): void {
    if (!localStorage.getItem('overallData')) {
      localStorage.setItem('overallData', JSON.stringify(this.initialData));
    }

    if (!localStorage.getItem('apiData')) {
      localStorage.setItem('apiData', JSON.stringify(this.data));
    }
  }
  
}